### ISSUE TITLE
Error: Unexpected token

### ISSUE THREAD

**Issue by risalfajar** [chicoxyzzy/node-releases#30]
I am using Svelte with Nollup, when i'm trying to build my project with dev configuration, it throw this error (view the image to know where the error is):

![image](https://user-images.githubusercontent.com/28381124/162588977-3c1d97af-1ec5-468b-b191-81131fa30f1e.png)

```
ParseError: /node_modules/node-releases/data/release-schedule/release-schedule.json
SyntaxError: Unexpected token (1:7)
    {"v0.8":{"start":"2012-06-25","end":"2014-07-31"},"v0.10":{"start":"2013-03-11","end":"2016-10-31"},"v0.12":{"start":"2015-02-06","end":"2016-12-31"},"v4":{"start":"2015-09-08","lts":"2015-10-12","maintenance":"2017-04-01","end":"2018-04-30","codename":"Argon"},"v5":{"start":"2015-10-29","maintenance":"2016-04-30","end":"2016-06-30"},"v6":{"start":"2016-04-26","lts":"2016-10-18","maintenance":"2018-04-30","end":"2019-04-30","codename":"Boron"},"v7":{"start":"2016-10-25","maintenance":"2017-04-30","end":"2017-06-30"},"v8":{"start":"2017-05-30","lts":"2017-10-31","maintenance":"2019-01-01","end":"2019-12-31","codename":"Carbon"},"v9":{"start":"2017-10-01","maintenance":"2018-04-01","end":"2018-06-30"},"v10":{"start":"2018-04-24","lts":"2018-10-30","maintenance":"2020-05-19","end":"2021-04-30","codename":"Dubnium"},"v11":{"start":"2018-10-23","maintenance":"2019-04-22","end":"2019-06-01"},"v12":{"start":"2019-04-23","lts":"2019-10-21","maintenance":"2020-11-30","end":"2022-04-30","codename":"Erbium"},"v13":{"start":"2019-10-22","maintenance":"2020-04-01","end":"2020-06-01"},"v14":{"start":"2020-04-21","lts":"2020-10-27","maintenance":"2021-10-19","end":"2023-04-30","codename":"Fermium"},"v15":{"start":"2020-10-20","maintenance":"2021-04-01","end":"2021-06-01"},"v16":{"start":"2021-04-20","lts":"2021-10-26","maintenance":"2022-10-18","end":"2024-04-30","codename":"Gallium"},"v17":{"start":"2021-10-19","maintenance":"2022-04-01","end":"2022-06-01"},"v18":{"start":"2022-04-19","lts":"2022-10-25","maintenance":"2023-10-18","end":"2025-04-30","codename":""}}
           ^
    at compileModule (/home/risal/WebProjects/si-mantu-mantap-web/hosting/node_modules/nollup/lib/impl/NollupCompiler.js:211:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async compileModule (/home/risal/WebProjects/si-mantu-mantap-web/hosting/node_modules/nollup/lib/impl/NollupCompiler.js:208:13)
    at async compileModule (/home/risal/WebProjects/si-mantu-mantap-web/hosting/node_modules/nollup/lib/impl/NollupCompiler.js:208:13)
    at async compileModule (/home/risal/WebProjects/si-mantu-mantap-web/hosting/node_modules/nollup/lib/impl/NollupCompiler.js:208:13)
    at async compileModule (/home/risal/WebProjects/si-mantu-mantap-web/hosting/node_modules/nollup/lib/impl/NollupCompiler.js:208:13)
    at async compileModule (/home/risal/WebProjects/si-mantu-mantap-web/hosting/node_modules/nollup/lib/impl/NollupCompiler.js:208:13)
    at async compileModule (/home/risal/WebProjects/si-mantu-mantap-web/hosting/node_modules/nollup/lib/impl/NollupCompiler.js:208:13)
    at async compileInputTarget (/home/risal/WebProjects/si-mantu-mantap-web/hosting/node_modules/nollup/lib/impl/NollupCompiler.js:243:5)
```

**Comment by risalfajar** [comment]
Version: 2.0.2

**Comment by risalfajar** [comment]
Nevermind. I've found the problem.

The culprit is `import { data } from 'autoprefixer'` which I imported by mistake, even if it's never been used.
